# Generated by Django 5.0.9 on 2026-01-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
