# Generated by Django 5.0.9 on 2026-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roombooking_num_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='cottage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='deluxe_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='family_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='suite_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room_type',
            field=models.CharField(blank=True, choices=[('cottage', 'Cottage'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('family', 'Family')], max_length=20, null=True),
        ),
    ]
