# Generated by Django 5.0.9 on 2026-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_roombooking_cottage_count_roombooking_deluxe_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
