# Generated by Django 5.0.9 on 2026-01-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roombooking_breakfast_roombooking_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='lunch',
        ),
    ]
