# Generated by Django 5.0.9 on 2026-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='booked_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booked_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
