# Generated by Django 5.0.9 on 2026-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventbooking_booked_by_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1_title', models.CharField(default='Welcome to Silvermoon Park', max_length=200)),
                ('slide1_subtitle', models.CharField(default='Where Luxury Meets Tranquility', max_length=300)),
                ('slide2_title', models.CharField(default='Unforgettable Experiences', max_length=200)),
                ('slide2_subtitle', models.CharField(default='Create Memories That Last Forever', max_length=300)),
                ('slide3_title', models.CharField(default='Premium Accommodations', max_length=200)),
                ('slide3_subtitle', models.CharField(default='Comfort & Elegance in Every Detail', max_length=300)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='info@silvermoonpark.com', max_length=254)),
                ('address', models.TextField(default='Silvermoon Park Resort, Nature Valley, India')),
                ('map_link', models.URLField(blank=True, default='https://maps.google.com', max_length=500)),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/silvermoonpark', max_length=300)),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/silvermoonpark', max_length=300)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/silvermoonpark', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
