# Generated by Django 5.0.9 on 2026-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitecontent_eventbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='map_link',
            field=models.TextField(blank=True, default='https://maps.google.com'),
        ),
    ]
