# Generated by Django 5.0.9 on 2026-01-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_explorecard_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
