# Generated by Django 5.0.9 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_galleryimage_deleted_at_galleryimage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorecard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explorecard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='explorecard',
            name='full_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
